name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Extract and Locate Files
        run: |
          unzip Red-Eye-Mobile-main.zip
          # Nggoleki folder sing isine gradlew lan mindah kabeh isine neng kene
          GRADLEW_DIR=$(find . -name "gradlew" -printf '%h\n' | head -n 1)
          if [ -n "$GRADLEW_DIR" ]; then
            cp -r $GRADLEW_DIR/* . || true
          fi
          chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: "**/build/outputs/apk/debug/*.apk"
