name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Extract and Downgrade Gradle
        run: |
          unzip Red-Eye-Mobile-main.zip
          cp -r Red-Eye-Mobile-main/* . || true
          
          # IKI JIMATE: Paksa nganggo Gradle 8.2 ben cocok karo kodingan lawas
          gradle wrapper --gradle-version 8.2
          chmod +x gradlew

      - name: Build with Gradle
        # Nganggo --no-daemon ben memori HP/server ora abot
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: "**/build/outputs/apk/debug/*.apk"
