name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Extract Project
        run: |
          unzip Red-Eye-Mobile-main.zip
          cp -r Red-Eye-Mobile-main/* . || true
          # Iki jimat ben file gradlew-ne ketemu senajan neng njero folder
          find . -name "gradlew" -exec chmod +x {} +

      - name: Build with Gradle
        run: |
          # Nggoleki path gradlew kanthi otomatis
          GRADLEW_PATH=$(find . -name "gradlew" | head -n 1)
          $GRADLEW_PATH assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: "**/build/outputs/apk/debug/*.apk"
